config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"

  namespace "api", defaults: { format: :json } do
    namespace "v1" do
      resources :users, only: [:create]

      resources :teams, only: [], param: :team_id do
        collection do
          resources :news, only: %i[create index]
        end
      end
    end
  end

  namespace "app" do
    resources :users
    resources :teams
  end

  root to: "app/users#index"
end

app/models/news.rb
class News < ApplicationRecord
  resourcify

  belongs_to :team

  validates :title, presence: true
  validates :body, presence: true
end

app/models/presenters/news/alexa.rb
module Presenters
  module News
    module Alexa
      def self.parse(news)
        [news].flatten.map do |item|
          {
            uid: item.id,
            updateDate: item.updated_at,
            titleText: item.title,
            mainText: item.body,
            redirectionUrl: item.link
          }
        end
      end
    end
  end
end

app/controllers/api/v1/news_controller.rb
module Api
  module V1
    class NewsController < Api::V1::ApiController
      def index
        render json: Presenters::News::Alexa.parse(current_team.news)
      end

      def create
        @news = current_team.news.new(news_params)

        if @news.save
          head :ok
        else
          render json: @news.errors, status: :unprocessable_entity
        end
      end

      private

      def news_params
        params.permit(:body, :title, :link)
      end
    end
  end
end

app/controllers/app/news_controller.rb
module App
  class NewsController < ApplicationController
    before_action :set_news, only: %i[show edit update destroy]

    # GET /news
    # GET /news.json
    def index
      @news = News.all
    end

    # GET /news/1
    # GET /news/1.json
    def show; end

    # GET /news/new
    def new
      @news = News.new
    end

    # GET /news/1/edit
    def edit; end

    # POST /news
    # POST /news.json
    def create
      @news = News.new(news_params)

      respond_to do |format|
        if @news.save
          format.html { redirect_to @news, notice: "News was successfully created." }
          format.json { render :show, status: :created, location: @news }
        else
          format.html { render :new }
          format.json { render json: @news.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /news/1
    # PATCH/PUT /news/1.json
    def update
      respond_to do |format|
        if @news.update(news_params)
          format.html { redirect_to @news, notice: "News was successfully updated." }
          format.json { render :show, status: :ok, location: @news }
        else
          format.html { render :edit }
          format.json { render json: @news.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /news/1
    # DELETE /news/1.json
    def destroy
      @news.destroy
      respond_to do |format|
        format.html { redirect_to news_index_url, notice: "News was successfully destroyed." }
        format.json { head :no_content }
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def news_params
      params.require(:news).permit(:team_id, :body)
    end
  end
end

app/views/app/news/_form.html.erb
<%= form_with(model: news, local: true) do |form| %>
  <% if news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(news.errors.count, "error") %> prohibited this news from being saved:</h2>

      <ul>
        <% news.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :team_id %>
    <%= form.number_field :team_id %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_field :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/app/news/edit.html.erb
<h1>Editing News</h1>

<%= render 'form', news: @news %>

<%= link_to 'Show', @news %> |
<%= link_to 'Back', news_index_path %>

app/views/app/news/index.html.erb
<p id="notice"><%= notice %></p>

<h1>News</h1>

<table>
  <thead>
    <tr>
      <th>Team</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @news.each do |news| %>
      <tr>
        <td><%= news.team_id %></td>
        <td><%= news.body %></td>
        <td><%= link_to 'Show', news %></td>
        <td><%= link_to 'Edit', edit_news_path(news) %></td>
        <td><%= link_to 'Destroy', news, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New News', new_news_path %>

app/views/app/news/new.html.erb
<h1>New News</h1>

<%= render 'form', news: @news %>

<%= link_to 'Back', news_index_path %>

app/views/app/news/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Team:</strong>
  <%= @news.team_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @news.body %>
</p>

<%= link_to 'Edit', edit_news_path(@news) %> |
<%= link_to 'Back', news_index_path %>