config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"

  namespace "api", defaults: { format: :json } do
    namespace "v1" do
      resources :users, only: [:create]

      resources :teams, only: [], param: :team_id do
        collection do
          resources :news, only: %i[create index]
        end
      end
    end
  end

  namespace "app" do
    resources :users
    resources :teams
  end

  root to: "app/users#index"
end

app/models/user.rb
class User < ApplicationRecord
  resourcify
  rolify

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :recoverable,
         :registerable, :rememberable, :validatable

  belongs_to :team, optional: true

  rails_admin do
    list do
      field :id
      field :email
      field :amazon_user_id
      field :team
      field :roles
      field :created_at
      field :updated_at
    end

    object_label_method do
      :label
    end
  end

  def label
    name || email
  end
end

app/controllers/api/v1/users_controller.rb
module Api
  module V1
    class UsersController < Api::V1::ApiController
      def create
        user = User.find_by("amazon_user_id = ? OR email = ?",
                            *user_params.slice(:amazon_user_id, :email).values)

        if user.present?
          user.update!(user_params)
        else
          User.create!(user_params)
        end

        head :ok
      end

      private

      def user_params
        params
          .permit(:email, :name, :amazon_user_id)
          .merge(
            password: Devise.friendly_token
          )
      end
    end
  end
end

app/controllers/app/users_controller.rb
module App
  class UsersController < ApplicationController
    before_action :set_user, only: %i[show edit update destroy]

    # GET /users
    # GET /users.json
    def index
      @users = User.all
    end

    # GET /users/1
    # GET /users/1.json
    def show; end

    # GET /users/new
    def new
      @user = User.new
    end

    # GET /users/1/edit
    def edit; end

    # POST /users
    # POST /users.json
    def create
      @user = User.new(user_params)

      respond_to do |format|
        if @user.save
          format.html { redirect_to @user, notice: "User was successfully created." }
          format.json { render :show, status: :created, location: @user }
        else
          format.html { render :new }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /users/1
    # PATCH/PUT /users/1.json
    def update
      respond_to do |format|
        if @user.update(user_params)
          format.html { redirect_to @user, notice: "User was successfully updated." }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /users/1
    # DELETE /users/1.json
    def destroy
      @user.destroy
      respond_to do |format|
        format.html { redirect_to app_users_url, notice: "User was successfully destroyed." }
        format.json { head :no_content }
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.fetch(:user, {})
    end
  end
end

app/helpers/app/users_helper.rb
module App::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/app/users/_form.html.erb
<%= form_with(model: [:app, user], local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/app/users/_users_list.html.erb
<table class="table-auto">
  <thead>
    <tr class="text-left">
      <th class="px-4 py-2">Id</th>
      <th class="px-4 py-2">Email</th>
      <th class="px-4 py-2">Nome</th>
      <th class="px-4 py-2">Time</th>
      <th class="px-4 py-2">Ações</th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td class="border px-4 py-2"><%= user.amazon_user_id[-6..] %></td>
        <td class="border px-4 py-2"><%= user.email %></td>
        <td class="border px-4 py-2"><%= user.name %></td>
        <td class="border px-4 py-2"></td>

        <td class="border px-4 py-2">
          <%= link_to 'Show', [:app, user] %>
          <%= link_to 'Edit', edit_app_user_path(user) %>
          <%= link_to 'Destroy', [:app, user], method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/app/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', [:app, @user] %> |
<%= link_to 'Back', app_users_path %>

app/views/app/users/index.html.erb
<%= render "users_list", users: @users %>

app/views/app/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/app/users/show.html.erb
<p>
  <strong>Nome:</strong>
  <%= @user.name %>
</p>
<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>
<p>
  <strong>Time:</strong>
  <%= link_to @user.team.name, app_team_path(@user.team) %>
</p>
<p>
  <strong>Amazon ID:</strong>
  <%= @user.amazon_user_id[-6..] %>
</p>

<%= link_to 'Edit', edit_app_user_path(@user) %> |
<%= link_to 'Back', app_users_path %>