config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"

  namespace "api", defaults: { format: :json } do
    namespace "v1" do
      resources :users, only: [:create]

      resources :teams, only: [], param: :team_id do
        collection do
          resources :news, only: %i[create index]
        end
      end
    end
  end

  namespace "app" do
    resources :users
    resources :teams
  end

  root to: "app/users#index"
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :users
  has_many :news

  before_create :generate_access_token

  rails_admin do
    list do
      field :id
      field :name
      field :users
      field :news
      field :created_at
      field :updated_at
    end
  end

  def generate_access_token
    self.access_token = SecureRandom.hex
  end
end

app/controllers/app/teams_controller.rb
module App
  class TeamsController < ApplicationController
    before_action :set_team, only: %i[show edit update destroy]

    # GET /teams
    # GET /teams.json
    def index
      @teams = Team.all
    end

    # GET /teams/1
    # GET /teams/1.json
    def show; end

    # GET /teams/new
    def new
      @team = Team.new
    end

    # GET /teams/1/edit
    def edit; end

    # POST /teams
    # POST /teams.json
    def create
      @team = Team.new(team_params)

      respond_to do |format|
        if @team.save
          format.html { redirect_to [:app, @team], notice: "Team was successfully created." }
          format.json { render :show, status: :created, location: @team }
        else
          format.html { render :new }
          format.json { render json: @team.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /teams/1
    # PATCH/PUT /teams/1.json
    def update
      respond_to do |format|
        if @team.update(team_params)
          format.html { redirect_to [:app, @team], notice: "Team was successfully updated." }
          format.json { render :show, status: :ok, location: @team }
        else
          format.html { render :edit }
          format.json { render json: @team.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /teams/1
    # DELETE /teams/1.json
    def destroy
      @team.destroy
      respond_to do |format|
        format.html { redirect_to app_teams_url, notice: "Team was successfully destroyed." }
        format.json { head :no_content }
      end
    end

    private

    def set_team
      @team = Team.find(params[:id])
    end

    def team_params
      params.require(:team).permit(:name)
    end
  end
end

app/views/app/teams/_form.html.erb
<%= form_with(model: [:app, team], local: true, class: "w-full max-w-lg") do |form| %>
  <% if team.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(team.errors.count, "error") %> prohibited this team from being saved:</h2>

      <ul>
        <% team.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="md:flex md:items-center mb-6">
    <div class="md:max-w-1/3 m-2">
      <%= form.label :name, "Nome", class: 'block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4' %>
    </div>
    <div class="w-2/3 md:w-1/3 m-2">
      <%= form.text_field :name, value: team.name, class: 'bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500' %>
    </div>
    <div class="md:w-1/3 m-2">
      <%= form.submit "Atualizar", class: "shadow hover:bg-gray-400 focus:shadow-outline focus:outline-none font-bold py-2 px-4 rounded" %>
    </div>
  </div>
<% end %>

app/views/app/teams/edit.html.erb
<div class="p-4">
  <h1>Time: <%= @team.name %></h1>

  <%= render 'form', team: @team %>

  <div>
    <%= link_to 'Lista de times', app_teams_path, class: 'inline-block align-baseline font-bold text-sm hover:text-gray-900' %>
  </div>
</div>

app/views/app/teams/index.html.erb
<table class="table-auto">
  <thead>
    <tr class="text-left">
      <th class="px-4 py-2">Name</th>
      <th class="px-4 py-2" colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @teams.each do |team| %>
      <tr>
        <td class="border px-4 py-2"><%= team.name %></td>
        <td class="border px-4 py-2">
          <%= link_to 'Show', app_team_path(team) %>
          <%= link_to 'Edit', edit_app_team_path(team) %>
          <%= link_to 'Destroy', app_team_path(team), method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Team', new_app_team_path %>

app/views/app/teams/new.html.erb
<h1>New Team</h1>

<%= render 'form', team: @team %>

<%= link_to 'Back', app_teams_path %>

app/views/app/teams/show.html.erb
<p>
  <strong>Nome do time:</strong>
  <%= @team.name %>
</p>

<%= render "app/users/users_list", users: @team.users %>

<%= link_to 'Edit', edit_app_team_path(@team) %> |
<%= link_to 'Back', app_teams_path %>